# -*- coding: utf-8 -*-
"""Listas 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJbwrRiEL1yR66B8A80qgF7e9xrnUIW8

# Juntar Listas, Ordenar e Cuidados Especiais

### 2 formas:

- lista1.extend(lista2)
- lista_nova = lista1 + lista2

Obs: o Método .append não junta listas, mas adiciona um valor no final da lista
"""

produtos = ['apple tv', 'mac', 'iphone x', 'iphone 11', 'IPad', 'apple watch', 'mac book', 'airpods']
novos_produtos = ['iphone 12', 'ioculos']

"""### Cuidado:

- [1] + [2] não é a mesma coisa que 1 + 2, então cuidado sempre com o formato dos valores na hora de fazer operações.
"""

vendas = [1000, 1500, 15000, 20000, 270, 900, 100, 1200]
vendas_iphonex = [15000]
vendas_iphone11 = [20000]

"""### Ordenar listas

lista.sort()
lista.sort(reverse=True)  - inverter a ordem, maior para menor
"""

