# -*- coding: utf-8 -*-
"""Listas 05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYyQHisbLGJDJgpQdc9_tRBiyoS3rQea

# Algumas Funções Básicas de Lista

## Tamanho da Lista

tamanho = len(lista)
"""

produtos = ['apple tv', 'mac', 'iphone x', 'IPad', 'apple watch', 'mac book', 'airpods']

"""- Quantos produtos temos a venda?"""



## Maior e Menor Valor

maior = max(lista)

menor = min(lista)


vendas = [1000, 1500, 15000, 270, 900, 100, 1200]

"""- Qual o item mais vendido?
- Qual o item menos vendido?
"""

